### ISSUE TITLE
Removing default severity 'brutal' for perlcritic

### ISSUE THREAD

**Issue by glauschwuffel** [zhiyuan-lin/vscode-perl#2]
Hi there,

thanks for writing the extension for Visual Studio Code! It almost worked out of the box for me.

One thing I had to patch though was the default setting of '--brutal' when calling perlcritic. I work in several Perl projects and we never got down to that level yet :)  Usually we configure the severity level we want to use in the .perlcriticrc.

By calling perlcritic with '--brutal' this configuration isn't respected, so I removed the argument.

I think by merging [my PR](#1) your extension could be useful for more developers out of the box.

Thanks for your time!

**Comment by zhiyuan-lin** [comment]
Thank you @glauschwuffel , since I only used `--brutal` exclusively I did not know that it prevent customization in `.perlcriticrc`
I will merge your PR now.
